"""enforce same user dependency ownership

Revision ID: 7f8029ae08bd
Revises: 9925f3cea052
Create Date: 2026-09-29 12:42:22.635943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8029ae08bd'
down_revision: Union[str, Sequence[str], None] = '9925f3cea052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dependency_relationships_target_service_id_fkey'), 'dependency_relationships', type_='foreignkey')
    op.drop_constraint(op.f('dependency_relationships_source_service_id_fkey'), 'dependency_relationships', type_='foreignkey')

    op.create_unique_constraint(
        'uq_service_accounts_user_id_id',
        'service_accounts',
        ['user_id', 'id'],
    )

    op.create_foreign_key(
        'fk_dependency_source_same_user',
        'dependency_relationships',
        'service_accounts',
        ['user_id', 'source_service_id'],
        ['user_id', 'id'],
        ondelete='CASCADE',
    )

    op.create_foreign_key(
        'fk_dependency_target_same_user',
        'dependency_relationships',
        'service_accounts',
        ['user_id', 'target_service_id'],
        ['user_id', 'id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_accounts_user_id_id', 'service_accounts', type_='unique')
    op.drop_constraint('fk_dependency_target_same_user', 'dependency_relationships', type_='foreignkey')
    op.drop_constraint('fk_dependency_source_same_user', 'dependency_relationships', type_='foreignkey')
    op.create_foreign_key(op.f('dependency_relationships_source_service_id_fkey'), 'dependency_relationships', 'service_accounts', ['source_service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dependency_relationships_target_service_id_fkey'), 'dependency_relationships', 'service_accounts', ['target_service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
