"""add recovery methods and dependency relationships

Revision ID: 9925f3cea052
Revises: a599c904c317
Create Date: 2026-09-29 12:36:46.222948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9925f3cea052'
down_revision: Union[str, Sequence[str], None] = 'a599c904c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_service_id', sa.UUID(), nullable=False),
    sa.Column('target_service_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('two_factor_for', 'login_identity_for', 'recovery_channel_for', 'controls', 'hosts', 'billing_for', 'required_for', 'other', name='dependency_type_enum'), nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_service_id <> target_service_id', name='ck_dependency_no_self_reference'),
    sa.ForeignKeyConstraint(['source_service_id'], ['service_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_service_id'], ['service_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_service_id', 'target_service_id', 'relationship_type', name='uq_dependency_relationship')
    )
    op.create_index(op.f('ix_dependency_relationships_user_id'), 'dependency_relationships', ['user_id'], unique=False)
    op.create_index('ix_dependency_source_target', 'dependency_relationships', ['source_service_id', 'target_service_id'], unique=False)
    op.create_index('ix_dependency_target_source', 'dependency_relationships', ['target_service_id', 'source_service_id'], unique=False)
    op.create_table('recovery_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_account_id', sa.UUID(), nullable=False),
    sa.Column('method_type', sa.Enum('recovery_email', 'phone_number', 'authenticator_app', 'backup_codes', 'trusted_device', 'security_key', 'support_process', 'other', name='recovery_method_type_enum'), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_methods_service_account_id'), 'recovery_methods', ['service_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_methods_service_account_id'), table_name='recovery_methods')
    op.drop_table('recovery_methods')
    op.drop_index('ix_dependency_target_source', table_name='dependency_relationships')
    op.drop_index('ix_dependency_source_target', table_name='dependency_relationships')
    op.drop_index(op.f('ix_dependency_relationships_user_id'), table_name='dependency_relationships')
    op.drop_table('dependency_relationships')
    # ### end Alembic commands ###
