"""add audit events

Revision ID: d2da1163648a
Revises: fc67e340ac7b
Create Date: 2026-09-29 12:57:45.917889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2da1163648a'
down_revision: Union[str, Sequence[str], None] = 'fc67e340ac7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('user_login', 'user_logout', 'service_created', 'service_updated', 'service_deleted', 'dependency_created', 'dependency_deleted', 'incident_created', 'incident_updated', 'incident_resolved', 'impact_analyzed', 'recovery_plan_created', 'recovery_plan_updated', 'recovery_action_started', 'recovery_action_completed', 'recovery_action_failed', 'security_event', 'other', name='audit_event_type_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_user_event_type', 'audit_events', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_user_event_type', table_name='audit_events')
    op.drop_index('ix_audit_events_user_created', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
