"""add incidents and cascading impact tracking

Revision ID: f904f063367f
Revises: 7f8029ae08bd
Create Date: 2026-09-29 12:48:29.851864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f904f063367f'
down_revision: Union[str, Sequence[str], None] = '7f8029ae08bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('root_service_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.Enum('access_lost', 'device_lost', 'compromised', 'credential_failure', 'recovery_failure', 'service_unavailable', 'other', name='incident_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'analyzing', 'recovering', 'resolved', name='incident_status_enum'), server_default='open', nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity_enum'), server_default='medium', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'root_service_id'], ['service_accounts.user_id', 'service_accounts.id'], name='fk_incident_root_service_same_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_incidents_user_id_id')
    )
    op.create_index(op.f('ix_incidents_root_service_id'), 'incidents', ['root_service_id'], unique=False)
    op.create_index('ix_incidents_user_created_at', 'incidents', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    op.create_index('ix_incidents_user_status', 'incidents', ['user_id', 'status'], unique=False)
    op.create_table('incident_impacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('service_account_id', sa.UUID(), nullable=False),
    sa.Column('impact_type', sa.Enum('root', 'direct', 'indirect', name='impact_type_enum'), nullable=False),
    sa.Column('dependency_depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('impact_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('is_access_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'incident_id'], ['incidents.user_id', 'incidents.id'], name='fk_incident_impact_incident_same_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'service_account_id'], ['service_accounts.user_id', 'service_accounts.id'], name='fk_incident_impact_service_same_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'service_account_id', name='uq_incident_impact_service')
    )
    op.create_index('ix_incident_impacts_incident_depth', 'incident_impacts', ['incident_id', 'dependency_depth'], unique=False)
    op.create_index(op.f('ix_incident_impacts_incident_id'), 'incident_impacts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_impacts_service_account_id'), 'incident_impacts', ['service_account_id'], unique=False)
    op.create_index(op.f('ix_incident_impacts_user_id'), 'incident_impacts', ['user_id'], unique=False)
    op.create_index('ix_incident_impacts_user_incident', 'incident_impacts', ['user_id', 'incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_impacts_user_incident', table_name='incident_impacts')
    op.drop_index(op.f('ix_incident_impacts_user_id'), table_name='incident_impacts')
    op.drop_index(op.f('ix_incident_impacts_service_account_id'), table_name='incident_impacts')
    op.drop_index(op.f('ix_incident_impacts_incident_id'), table_name='incident_impacts')
    op.drop_index('ix_incident_impacts_incident_depth', table_name='incident_impacts')
    op.drop_table('incident_impacts')
    op.drop_index('ix_incidents_user_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index('ix_incidents_user_created_at', table_name='incidents')
    op.drop_index(op.f('ix_incidents_root_service_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
