"""add recovery plans and recovery actions

Revision ID: fc67e340ac7b
Revises: f904f063367f
Create Date: 2026-09-29 12:53:16.485625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc67e340ac7b'
down_revision: Union[str, Sequence[str], None] = 'f904f063367f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'in_progress', 'completed', 'failed', name='recovery_plan_status_enum'), server_default='draft', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'incident_id'], ['incidents.user_id', 'incidents.id'], name='fk_recovery_plan_incident_same_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_recovery_plans_user_id_id')
    )
    op.create_index('ix_recovery_plans_incident_created', 'recovery_plans', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recovery_plans_incident_id'), 'recovery_plans', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_plans_user_id'), 'recovery_plans', ['user_id'], unique=False)
    op.create_index('ix_recovery_plans_user_status', 'recovery_plans', ['user_id', 'status'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recovery_plan_id', sa.UUID(), nullable=False),
    sa.Column('service_account_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('restore_access', 'verify_recovery_method', 'reset_credential', 'reconfigure_2fa', 'verify_dependency', 'contact_support', 'security_review', 'other', name='recovery_action_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', 'blocked', 'failed', name='recovery_action_status_enum'), server_default='pending', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('blocking_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'recovery_plan_id'], ['recovery_plans.user_id', 'recovery_plans.id'], name='fk_recovery_action_plan_same_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'service_account_id'], ['service_accounts.user_id', 'service_accounts.id'], name='fk_recovery_action_service_same_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_plan_id', 'step_order', name='uq_recovery_action_plan_step')
    )
    op.create_index('ix_recovery_actions_plan_status', 'recovery_actions', ['recovery_plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_recovery_plan_id'), 'recovery_actions', ['recovery_plan_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_service_account_id'), 'recovery_actions', ['service_account_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_user_id'), 'recovery_actions', ['user_id'], unique=False)
    op.create_index('ix_recovery_actions_user_service', 'recovery_actions', ['user_id', 'service_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_actions_user_service', table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_user_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_service_account_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_recovery_plan_id'), table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_plan_status', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_recovery_plans_user_status', table_name='recovery_plans')
    op.drop_index(op.f('ix_recovery_plans_user_id'), table_name='recovery_plans')
    op.drop_index(op.f('ix_recovery_plans_incident_id'), table_name='recovery_plans')
    op.drop_index('ix_recovery_plans_incident_created', table_name='recovery_plans')
    op.drop_table('recovery_plans')
    # ### end Alembic commands ###
